export const FETCH_FAULT_TYPES = 'FETCH_FAULT_TYPES'
export const STORE_GROUPS = 'STORE_GROUPS'
export const FETCH_GROUPS = 'FETCH_GROUPS'
export const SHOW_GROUPS = 'SHOW_GROUPS'
export const ASSIGN_GROUP = 'ASSIGN_GROUP'
export const ASSIGN_FAULT_TO_GROUP ='ASSIGN_FAULT_TO_GROUP';
export const UPDATE_GROUP = 'UPDATE_GROUP'